name: Python package

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install libraries
      run: |
        pip install requests
        pip install pandas
        pip install beautifulsoup4
        pip install lxml
        pip install selenium
        pip install webdriver_manager
       
    - name: Run Python script
      run: |
        python3 travelrank.py

    - name: Configure Git
      run: |
        git config --global user.email "kjw040416@gmail.com"
        git config --global user.name "KIMJW04"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Committing travel chart data"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        branch: "main"
